GATE_BAUD_RATE = 9600
GATE_USB_PORT = "/dev/ttyUSB0"
GATE_ADDRESS = 0x05

HIKVISION_IP = "192.168.2.64"
HIKVISION_PORT = "80"
HIKVISION_HOST = f'http://{HIKVISION_IP}:{HIKVISION_PORT}'
HIKVISION_ID = 'admin'
HIKVISION_PASSWORD = '-arngnennscfrer2'